drop table FemalName;
Create table [dbo].[FemalName](
[ID] Int not null primary key ,
[race_id] int not null REFERENCES Race (Id_Race),
[femalName] text not null
);
select * from Race

BEGIN
	INSERT FemalName Values(26,2,'Амафрея')
    INSERT FemalName Values(27,2,'Бетха')
	INSERT FemalName Values(28,2,'Вестра')
	INSERT FemalName Values(29,2,'Кетра')
	INSERT FemalName Values(30,2,'Мара')
	INSERT FemalName Values(31,2,'Ольга')
	INSERT FemalName Values(32,2,'Силифрей')
	INSERT FemalName Values(33,2,'Цефрея')
	INSERT FemalName Values(34,2,'Балама')
	INSERT FemalName Values(35,2,'Вонда')
	INSERT FemalName Values(36,2,'Джалана')
	INSERT FemalName Values(37,2,'Дона')
	INSERT FemalName Values(38,2,'Куара')
	INSERT FemalName Values(39,2,'Луиза')
	INSERT FemalName Values(40,2,'Марта')
	INSERT FemalName Values(41,2,'Селизе')
	INSERT FemalName Values(42,2,'Фаила')
	INSERT FemalName Values(43,2,'Бай')
	INSERT FemalName Values(44,2,'Ксяо')
	INSERT FemalName Values(45,2,'Лей')
	INSERT FemalName Values(46,2,'Мей')
	INSERT FemalName Values(47,2,'Тай')
	INSERT FemalName Values(48,2,'Цзя')
	INSERT FemalName Values(49,2,'Чао')
	INSERT FemalName Values(50,2,'Шуй')

	INSERT FemalName Values(51,3,'Бимпноттин')
    INSERT FemalName Values(52,3,'Брина')
	INSERT FemalName Values(53,3,'Вейуокет')
	INSERT FemalName Values(54,3,'Доннела')
	INSERT FemalName Values(55,3,'Дувамил')
	INSERT FemalName Values(56,3,'Занна')
	INSERT FemalName Values(57,3,'Карамип')
	INSERT FemalName Values(58,3,'Карлин')
	INSERT FemalName Values(59,3,'Лилли')
	INSERT FemalName Values(60,3,'Лорилла')
	INSERT FemalName Values(61,3,'Лупмоттин')
	INSERT FemalName Values(62,3,'Маднаб')
	INSERT FemalName Values(63,3,'Никс')
	INSERT FemalName Values(64,3,'Нисса')
	INSERT FemalName Values(65,3,'Ода')
	INSERT FemalName Values(66,3,'Орла')
	INSERT FemalName Values(67,3,'Ройвин')
	INSERT FemalName Values(68,3,'Тана')
	INSERT FemalName Values(69,3,'Шамил')
	INSERT FemalName Values(70,3,'Эливик')
	INSERT FemalName Values(71,3,'Элиджобелл')
	INSERT FemalName Values(72,3,'Элла')
	INSERT FemalName Values(73,3,'Янтара')
	INSERT FemalName Values(74,3,'Виоланта')
	INSERT FemalName Values(75,3,'Хильдегарда')

	INSERT FemalName Values(76,4,'Бри')
    INSERT FemalName Values(77,4,'Вани')
	INSERT FemalName Values(78,4,'Верна')
	INSERT FemalName Values(79,4,'Джиллиан')
	INSERT FemalName Values(80,4,'Китри')
	INSERT FemalName Values(81,4,'Кора')
	INSERT FemalName Values(82,4,'Кэлли')
	INSERT FemalName Values(83,4,'Лавиния')
	INSERT FemalName Values(84,4,'Лидда')
	INSERT FemalName Values(85,4,'Мерла')
	INSERT FemalName Values(86,4,'Недда')
	INSERT FemalName Values(87,4,'Паэла')
	INSERT FemalName Values(88,4,'Портия')
	INSERT FemalName Values(89,4,'Серафина')
	INSERT FemalName Values(90,4,'Трим')
	INSERT FemalName Values(91,4,'Шаэна')
	INSERT FemalName Values(92,4,'Эндри')
	INSERT FemalName Values(93,4,'Юфемия')
	INSERT FemalName Values(94,4,'Шарлотта')
	INSERT FemalName Values(95,4,'Урсула')
	INSERT FemalName Values(96,4,'Эльба')
	INSERT FemalName Values(97,4,'Олимпия')
	INSERT FemalName Values(98,4,'Никодема')
	INSERT FemalName Values(99,4,'Ирмгарда')
	INSERT FemalName Values(100,4,'Вильгельмина')

	INSERT FemalName Values(101,5,'Адрие')
    INSERT FemalName Values(102,5,'Альтеа')
	INSERT FemalName Values(103,5,'Андрасте')
	INSERT FemalName Values(104,5,'Антинуа')
	INSERT FemalName Values(105,5,'Бетринна')
	INSERT FemalName Values(106,5,'Бирель')
	INSERT FemalName Values(107,5,'Валанте')
	INSERT FemalName Values(108,5,'Джеленетт')
	INSERT FemalName Values(109,5,'Друсилиа')
	INSERT FemalName Values(110,5,'Йелениа')
	INSERT FemalName Values(111,5,'Каэлинн')
	INSERT FemalName Values(112,5,'Квеленна')
	INSERT FemalName Values(113,5,'Квиласи')
	INSERT FemalName Values(114,5,'Кейлет')
	INSERT FemalName Values(115,5,'Ксанафия')
	INSERT FemalName Values(116,5,'Лешанна')
	INSERT FemalName Values(117,5,'Лиа')
	INSERT FemalName Values(118,5,'Миали')
	INSERT FemalName Values(119,5,'Мэриэль')
	INSERT FemalName Values(120,5,'Найвара')
	INSERT FemalName Values(121,5,'Силакви')
	INSERT FemalName Values(122,5,'Теирастра')
	INSERT FemalName Values(123,5,'Тиа')
	INSERT FemalName Values(124,5,'Фелосиаль')
	INSERT FemalName Values(125,5,'Шава')

	INSERT FemalName Values(126,6,'Адрие')
    INSERT FemalName Values(127,6,'Альтеа')
	INSERT FemalName Values(128,6,'Андрасте')
	INSERT FemalName Values(129,6,'Антинуа')
	INSERT FemalName Values(130,6,'Бетринна')
	INSERT FemalName Values(131,6,'Бирель')
	INSERT FemalName Values(132,6,'Валанте')
	INSERT FemalName Values(133,6,'Джеленетт')
	INSERT FemalName Values(134,6,'Друсилиа')
	INSERT FemalName Values(135,6,'Йелениа')
	INSERT FemalName Values(136,6,'Каэлинн')
	INSERT FemalName Values(137,6,'Квеленна')
	INSERT FemalName Values(138,6,'Квиласи')
	INSERT FemalName Values(139,6,'Кейлет')
	INSERT FemalName Values(140,6,'Ксанафия')
	INSERT FemalName Values(141,6,'Лешанна')
	INSERT FemalName Values(142,6,'Лиа')
	INSERT FemalName Values(143,6,'Миали')
	INSERT FemalName Values(144,6,'Мэриэль')
	INSERT FemalName Values(145,6,'Найвара')
	INSERT FemalName Values(146,6,'Силакви')
	INSERT FemalName Values(147,6,'Теирастра')
	INSERT FemalName Values(148,6,'Тиа')
	INSERT FemalName Values(149,6,'Фелосиаль')
	INSERT FemalName Values(150,6,'Шава')

END;

GO
select * from FemalName